name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: ng build --prod

      - name: Deploy to S3
        uses: aws-actions/amazon-s3-sync@v3
        with:
          source: ./dist/
          dest: s3://${{ secrets.AWS_S3_BUCKET }}
          aws-region: us-east-1
          follow-symlinks: false
          cache-control: max-age=604800,public
       

      - name: Invalidate CloudFront cache
        uses: aws-actions/invalidate-cloudfront-cache@v2
        with:
          distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: '/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
